/*
 * @Descripttion:
 * @Author: cbz
 * @Date: 2020-05-29 11:07:35
 * @LastEditors: cbz
 * @LastEditTime: 2020-12-18 19:03:11
 */
const menuConfig = [{
        name: 'baseConfig',
        value: '基础',
        opts: [{
                name: 'title',
                text: '标题',
                description: '表单的标题',
                default: '',
                editor: 'input',
                type: 'text',
                required: true,
            },
            {
                name: 'width',
                text: '宽度',
                description: '宽度',
                default: 400,
                min: 0,
                max: 2000,
                editor: 'input',
                type: 'number',
                required: true,
            },
            {
                name: 'height',
                text: '高度',
                description: '高度',
                default: 300,
                min: 0,
                max: 1500,
                editor: 'input',
                type: 'number',
                required: true,
            },
            {
                name: 'top',
                text: '偏上',
                description: '偏上',
                default: 0,
                min: 0,
                editor: 'input',
                type: 'number',
                required: true,
            },
            {
                name: 'left',
                text: '偏左',
                description: '偏左',
                default: 0,
                min: 0,
                editor: 'input',
                type: 'number',
                required: true,
            },
            {
                name: 'rotate',
                text: '旋转',
                description: '旋转',
                default: 0,
                min: 0,
                editor: 'input',
                type: 'number',
                required: true,
            },
            {
                name: 'zIndex',
                text: '图层层数',
                description: '图层层数',
                default: 2,
                editor: 'input',
                type: 'number',
                required: true,
            },
            {
                name: 'animate',
                text: '入场动画：',
                description: '入场动画',
                default: {
                    default: 'slideInLeft',
                    option: [
                        { label: 'bounce', value: 'bounce' },
                        { label: 'flash', value: 'flash' },
                        { label: 'pulse', value: 'pulse' },
                        { label: 'rubberBand', value: 'rubberBand' },
                        { label: 'swing', value: 'swing' },
                        { label: 'tada', value: 'tada' },
                        { label: 'wobble', value: 'wobble' },
                        { label: 'bounceIn', value: 'bounceIn' },
                        { label: 'bounceInDown', value: 'bounceInDown' },
                        { label: 'bounceInLeft', value: 'bounceInLeft' },
                        { label: 'bounceInRight', value: 'bounceInRight' },
                        { label: 'bounceInUp', value: 'bounceInUp' },
                        { label: 'fadeIn', value: 'fadeIn' },
                        { label: 'fadeInDown', value: 'fadeInDown' },
                        { label: 'fadeInDownBig', value: 'fadeInDownBig' },
                        { label: 'fadeInLeft', value: 'fadeInLeft' },
                        { label: 'fadeInLeftBig', value: 'fadeInLeftBig' },
                        { label: 'fadeInRight', value: 'fadeInRight' },
                        { label: 'fadeInRightBig', value: 'fadeInRightBig' },
                        { label: 'fadeInUp', value: 'fadeInUp' },
                        { label: 'fadeInUpBig', value: 'fadeInUpBig' },
                        { label: 'flip', value: 'flip' },
                        { label: 'flipInX', value: 'flipInX' },
                        { label: 'flipInY', value: 'flipInY' },
                        { label: 'rotateIn', value: 'rotateIn' },
                        { label: 'rotateInDownLeft', value: 'rotateInDownLeft' },
                        { label: 'rotateInDownRight', value: 'rotateInDownRight' },
                        { label: 'rotateInUpLeft', value: 'rotateInUpLeft' },
                        { label: 'rotateInUpRight', value: 'rotateInUpRight' },
                        { label: 'slideInDown', value: 'slideInDown' },
                        { label: 'slideInLeft', value: 'slideInLeft' },
                        { label: 'slideInRight', value: 'slideInRight' },
                        { label: 'rollIn', value: 'rollIn' },
                    ],
                },
                editor: 'select',
                type: 'select',
                required: false,
            },
            {
                name: 'selfAnimate',
                text: '组件动画：',
                description: '组件动画',
                default: {
                    default: 'selfAnimate_none',
                    option: [
                        { label: '无', value: 'selfAnimate_none' },
                        { label: '呼吸灯-弱', value: 'selfAnimate_breathingLight' },
                        { label: '呼吸灯-强', value: 'selfAnimate_breathingLight_strong' },
                        { label: '漂浮-弱', value: 'selfAnimate_float' },
                        { label: '漂浮-强', value: 'selfAnimate_float_strong' },
                    ],
                },
                editor: 'select',
                type: 'select',
                required: false,
            },
            {
                name: 'backgroundColor',
                text: '背景颜色',
                description: '选设置背景颜色',
                default: 'transparent',
                editor: 'input',
                type: 'color',
                required: false,
            },
            {
                name: 'background',
                text: '背景',
                description: '选择一个背景图片',
                default: '',
                editor: 'img',
                type: 'upload',
                required: false,
            }, {
                name: 'isOpenAdvanced',
                text: '',
                description: '',
                default: false,
                editor: '',
                type: '',
            },
        ],
    },
    {
        name: 'styleConfig',
        helpUrl: 'https://www.yuque.com/docs/share/df507b25-fe6d-4b0d-b641-ae39d0a79de1?# 《图表组件介绍》',
        value: '样式',
        opts: [], // 样式从option中动态获取
    },
    {
        name: 'dataConfig',
        value: '数据',
        helpUrl: 'https://www.yuque.com/docs/share/83e8d4e9-c197-44f0-b815-24724f7958b9?# 《api接口介绍》',
        opts: [{
                name: 'dataBindType',
                text: '数据绑定方式',
                description: '数据绑定方式',
                default: {
                    default: 'json',
                    option: [
                        { label: '静态JSON', value: 'json' },
                        { label: 'excel', value: 'excel' },
                        { label: 'API拉取', value: 'api' },
                        { label: 'SSE拉取', value: 'SSE' },
                    ],
                },
                editor: 'select',
                type: 'select',
                required: true,
                upType: ['api', 'excel', 'json', 'SSE',],
            },
            {
                name: 'url',
                text: '',
                description: '',
                default: '',
                editor: '',
                type: '',
                upType: ['api',],
            },
            {
                name: 'params',
                text: '',
                description: '',
                default: '',
                editor: '',
                type: '',
                upType: ['api',],

            },
            {
                name: 'method',
                text: '',
                description: '',
                default: { default: 'get' },
                editor: '',
                type: '',
                upType: ['api',],
            },
            {
                name: 'responseData',
                text: '',
                description: '',
                default: {},
                editor: '',
                type: '',
                upType: ['api',],
            },
            {
                name: 'dataPath',
                text: '',
                description: '',
                default: [],
                editor: '',
                type: '',
                upType: ['api',],
            },
           
          
            {
                name: 'refresh',
                text: '自动更新请求间隔(分钟)',
                description: '自动更新请求(分钟)',
                default: 10,
                editor: 'input',
                type: 'number',
                upType: ['api',],
            },
            {
                name: 'shareList',
                text: '共享组件',
                description: '共享组件',
                default: [],
                editor: 'input',
                type: 'share',
                upType: ['api',],
            },
            {
                name: 'debug',
                text: '调试',
                description: '调试',
                default: '',
                editor: 'button',
                type: 'button',
                upType: ['api',],
            },
            {
                name: 'dataConversionFunction',
                text: '',
                description: '',
                default: "",
                editor: '',
                type: 'function',
                upType: ['api',],
            },
            {
                name: 'staticJson',
                text: '静态JSON',
                description: '静态JSON',
                default: {},
                editor: 'input',
                type: 'array',
                upType: ['json'],
            },
            {
                name: 'excelUpload',
                text: '上传excel文件',
                description: '上传excel文件',
                default: {},
                editor: 'excel',
                type: 'upload',
                upType: ['excel'],
            },
            {
                name: 'excelData',
                text: 'excel数据',
                description: 'excel数据',
                default: {},
                editor: 'input',
                type: 'array',
                upType: ['excel'],
            },
            {
                name: 'SSEResponseData',
                text: '',
                description: '',
                default: {},
                editor: '',
                type: '',
                upType: ['SSE'],
            },
            {
                name: 'SSEDataPath',
                text: '',
                description: '',
                default: [],
                editor: '',
                type: '',
                upType: ['SSE'],

            },
            {
                name: 'debug',
                text: '调试',
                description: '调试',
                default: '',
                editor: 'button',
                type: 'button',
                upType: ['SSE'],
            },
            {
                name: 'SSEDataConversionFunction',
                text: '',
                description: '',
                default: "",
                editor: '',
                type: 'function',
                upType: ['SSE'],
            },
            {
                name: 'dataIsAdd',
                text: '',
                description: '',
                default: "",
                editor: '',
                type: '',
                upType: ['SSE'],
            },
            {
                name: 'dataMaxLength',
                text: '',
                description: '',
                default: "",
                editor: '',
                type: '',
                upType: ['SSE'],
            },

        ],
    },
    {
        name: 'interactiveConfig',
        value: '交互',
        opts: [{
            name: 'multLink',
            text: '绑定组件',
            description: '绑定组件',
            default: '',
            editor: 'interactive',
            type: 'interactive',
            required: true,
        }, ],
    },
    {
        name: 'mapLayer',
        value: '地图图层',
        bindType: ['lightCity'], // 绑定元素的type  当type==bindType才显示此选项
        opts: [{
            name: 'addModal',
            text: '增加3D模型',
            description: '增加3D模型',
            default: '',
            editor: 'button',
            type: 'button',
            required: true,
        }, ],
    },
];
export default menuConfig;